# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: general.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='general.proto',
  package='ev.algorithm.general',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rgeneral.proto\x12\x14\x65v.algorithm.general\"{\n\nGeneralReq\x12\x11\n\tstream_id\x18\x01 \x01(\t\x12\x12\n\nstream_url\x18\x02 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x03 \x01(\t\x12\x38\n\x0b\x63ustom_data\x18\x04 \x01(\x0b\x32#.ev.algorithm.general.CustomReqData\"\x81\x01\n\rCustomReqData\x12\x1f\n\x17\x64\x65\x63oding_only_keyframes\x18\x01 \x01(\x08\x12\x1b\n\x13\x63\x61llback_interval_s\x18\x02 \x01(\x05\x12\x17\n\x0fwhether_src_pic\x18\x03 \x01(\x08\x12\x19\n\x11whether_alarm_pic\x18\x04 \x01(\x08\"\xb4\x01\n\x0fGeneralResponse\x12\x12\n\nerror_code\x18\x01 \x01(\x05\x12\x11\n\terror_msg\x18\x02 \x01(\t\x12\x11\n\tstream_id\x18\x03 \x01(\t\x12\x12\n\ntime_stamp\x18\x04 \x01(\x03\x12\x0e\n\x06status\x18\x05 \x01(\x05\x12\x16\n\x0esrc_pic_buffer\x18\x06 \x01(\x0c\x12\x18\n\x10\x61larm_pic_buffer\x18\x07 \x01(\x0c\x12\x11\n\talgo_data\x18\x08 \x01(\t2j\n\x0eGeneralService\x12X\n\x07General\x12 .ev.algorithm.general.GeneralReq\x1a%.ev.algorithm.general.GeneralResponse\"\x00(\x01\x30\x01\x62\x06proto3'
)




_GENERALREQ = _descriptor.Descriptor(
  name='GeneralReq',
  full_name='ev.algorithm.general.GeneralReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_id', full_name='ev.algorithm.general.GeneralReq.stream_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stream_url', full_name='ev.algorithm.general.GeneralReq.stream_url', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='args', full_name='ev.algorithm.general.GeneralReq.args', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='custom_data', full_name='ev.algorithm.general.GeneralReq.custom_data', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=162,
)


_CUSTOMREQDATA = _descriptor.Descriptor(
  name='CustomReqData',
  full_name='ev.algorithm.general.CustomReqData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='decoding_only_keyframes', full_name='ev.algorithm.general.CustomReqData.decoding_only_keyframes', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='callback_interval_s', full_name='ev.algorithm.general.CustomReqData.callback_interval_s', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='whether_src_pic', full_name='ev.algorithm.general.CustomReqData.whether_src_pic', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='whether_alarm_pic', full_name='ev.algorithm.general.CustomReqData.whether_alarm_pic', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=294,
)


_GENERALRESPONSE = _descriptor.Descriptor(
  name='GeneralResponse',
  full_name='ev.algorithm.general.GeneralResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='error_code', full_name='ev.algorithm.general.GeneralResponse.error_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_msg', full_name='ev.algorithm.general.GeneralResponse.error_msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stream_id', full_name='ev.algorithm.general.GeneralResponse.stream_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='ev.algorithm.general.GeneralResponse.time_stamp', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='ev.algorithm.general.GeneralResponse.status', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='src_pic_buffer', full_name='ev.algorithm.general.GeneralResponse.src_pic_buffer', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alarm_pic_buffer', full_name='ev.algorithm.general.GeneralResponse.alarm_pic_buffer', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='algo_data', full_name='ev.algorithm.general.GeneralResponse.algo_data', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=477,
)

_GENERALREQ.fields_by_name['custom_data'].message_type = _CUSTOMREQDATA
DESCRIPTOR.message_types_by_name['GeneralReq'] = _GENERALREQ
DESCRIPTOR.message_types_by_name['CustomReqData'] = _CUSTOMREQDATA
DESCRIPTOR.message_types_by_name['GeneralResponse'] = _GENERALRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GeneralReq = _reflection.GeneratedProtocolMessageType('GeneralReq', (_message.Message,), {
  'DESCRIPTOR' : _GENERALREQ,
  '__module__' : 'general_pb2'
  # @@protoc_insertion_point(class_scope:ev.algorithm.general.GeneralReq)
  })
_sym_db.RegisterMessage(GeneralReq)

CustomReqData = _reflection.GeneratedProtocolMessageType('CustomReqData', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMREQDATA,
  '__module__' : 'general_pb2'
  # @@protoc_insertion_point(class_scope:ev.algorithm.general.CustomReqData)
  })
_sym_db.RegisterMessage(CustomReqData)

GeneralResponse = _reflection.GeneratedProtocolMessageType('GeneralResponse', (_message.Message,), {
  'DESCRIPTOR' : _GENERALRESPONSE,
  '__module__' : 'general_pb2'
  # @@protoc_insertion_point(class_scope:ev.algorithm.general.GeneralResponse)
  })
_sym_db.RegisterMessage(GeneralResponse)



_GENERALSERVICE = _descriptor.ServiceDescriptor(
  name='GeneralService',
  full_name='ev.algorithm.general.GeneralService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=479,
  serialized_end=585,
  methods=[
  _descriptor.MethodDescriptor(
    name='General',
    full_name='ev.algorithm.general.GeneralService.General',
    index=0,
    containing_service=None,
    input_type=_GENERALREQ,
    output_type=_GENERALRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GENERALSERVICE)

DESCRIPTOR.services_by_name['GeneralService'] = _GENERALSERVICE

# @@protoc_insertion_point(module_scope)
