FROM ccr.ccs.tencentyun.com/source/ev_passenger_cpu_ori:v0.1
COPY PRC /etc/localtime
RUN cd /usr/local/ev_sdk \
        && wget -O /vas_v4.3_cv3.4.tar.gz https://vas-1256261446.cos.ap-guangzhou.myqcloud.com/vas_v4.3_cv3.4.tar.gz  \
        && tar xf /vas_v4.3_cv3.4.tar.gz -C / \
        && rm -f /vas_v4.3_cv3.4.tar.gz \
        && sed -i 's#9999#9776#g' /usr/local/vas/local.conf \
        && rm -rf /usr/local/vas/vas_data \
        && chmod +x /usr/local/vas/vas_start_container.sh

CMD ["/usr/local/vas/vas_start_container.sh"]

